import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col p-3'>
          <div className='bg-slate-700 text-white py-2 '>
            <Navbar />
          </div>
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
